workflow:
  - sample-name
  - start-at
  - stop-at
  - qc-files
  - tma
  - viz
  - multi-formats
  - single-formats
  - illumination
  - segmentation
  - segmentation-channel
  - segmentation-recyze
  - segmentation-nuclear-channel
  - segmentation-membrane-channel
  - segmentation-max-projection
  - downstream
  - ilastik-model
  - mesmer-model
  - background
  - staging-method
  - cellpose-model
  - background-method
  - flowsom-model
  - scanpy-model
  - fastpg-model
  - naivestates-model
deprecated:
  quantification-mask: "--quant-opts '--masks ...'"
  illum: --start-at illumination
  core-opts: --coreograph-opts
  mask-spatial: "--quant-opts '--masks ...'"
  mask-add: "--quant-opts '--masks ...'"
  nstates-opts: --naivestates-opts
  quant-opts: --mcquant-opts
  cell-states: --downstream
  probability-maps: --segmentation
